### ISSUE TITLE
change the subject's icons

### ISSUE THREAD

**Issue by naogify** [coderdojo-kumano/coderdojo-kumano.github.io#6]
i'll change these icons.

<img width="1263" alt="2016-12-22 10 06 56" src="https://cloud.githubusercontent.com/assets/8760841/21411832/d1100e9a-c82e-11e6-92ab-1fb0c45d30f9.png">

**Comment by miya0001** [comment]
Related:
https://github.com/coderdojo-kumano/coderdojo-kumano.github.io/pull/8
